### ISSUE TITLE
vrrpd can't receive data anymore after change from backup to master mode

### ISSUE THREAD

**Issue by redbrain17** [fredbcode/Vrrpd#11]
Our arm device is running vrrpd 1.13 and connected via ethernet to a Teldat Atlas Station with vrrpd support.

The vrrpd is first in backup state, then we remove the ethernet cable to the remote station. The vrrpd changes into master state. Then we re-plug the cable again. The vrrpd is now still in master mode 
and can't receive data anymore from the socket after switching into the master mode. We would expect that vrrpd is switching back to backup mode but this didn't happen. 
 
The select call in vrrpd_read() fails and no data is received from the socket. In tcpdump we already saw the data from the remote station.

**Comment by fredbcode** [comment]
> Our arm device is running vrrpd 1.13 and connected via ethernet to a 
> Teldat Atlas Station with vrrpd support.
>

ok
>
> The vrrpd is first in backup state, then we remove the ethernet cable 
> to the remote station. The vrrpd changes into master state.
>

Incorrect, it should not
when the Ethernet cable is plugged and vrrpd stopped do you receive 
packets from an other source ?
Do you have something in syslog before you remove the cable ? Can you 
post a complete syslog file  - before and after you remove the cable -

> Then we re-plug the cable again. The vrrpd is now still in master mode
>

Very strange

> and can't receive data anymore from the socket after switching into 
> the master mode. We would expect that vrrpd is switching back to 
> backup mode but this didn't happen.
>
> The select call in vrrpd_read() fails and no data is received from the 
> socket. In tcpdump we already saw the data from the remote station.
>

Maybe vrrpd ("my" version I mean) is not compatible with ARM and all of 
this is related with your previous bug report, unfortunately I don't 
have this kind of hardware for testing ...
Do you have a vrrpd version from your Linux distribution ?

Also can you show your configuration files, please ?

PM: fredbmail -nospam- at -nospam- free.fr

**Comment by redbrain17** [comment]
we tested the same again with your offical debian package Advanced-Vrrpd-1.13-64bits.deb on a ubuntu pc (no arm, no patches)

    vrrpd -i eth0 -v1 -p100 -d1 192.168.100.2/24

    Aug 31 10:41:33 OptiPlex-7010 vrrpd[2973]: vrrpd version Advanced Vrrpd 1.13 starting...
    Aug 31 10:41:33 OptiPlex-7010 vrrpd[2973]: vrrpd virtual IP 192.168.100.2
    Aug 31 10:41:33 OptiPlex-7010 vrrpd[2973]: VRRP ID 1 on eth0:  - INIT State -
    Aug 31 10:43:25 OptiPlex-7010 vrrpd[2973]: VRRP ID 1 on eth0: 192.168.100.2 is down, we are now the master router.
    Aug 31 10:43:25 OptiPlex-7010 vrrpd[2973]: VRRP ID 1 change MAC eth0


we saw the same behavior. Here a picture of our setup:
![vrrpd](https://cloud.githubusercontent.com/assets/175019/9575510/b4d1c516-4fd0-11e5-8225-487819c11c1d.png)

**Comment by fredbcode** [comment]
OK It's more clear now, I understand 

FI you can just write:
vrrpd -i eth0 -v 1 192.168.100.2

Can you try this please

1 - Stop vrrpd on Ubuntu
2 - Make a trace with tcpdump ( tcpdump -i eth0 -n | grep -v VRR )

You must receive VRRPD packets from Teldat 

Also can you check the switch, the spanning tree - stg - must be disabled

**Comment by fredbcode** [comment]
From Teldat, interface IP is 192.168.100.2 same as the VIP
So when vrrpd from Teldat is Backup 192.168.100.2 still present on the lan ...
I guess the switch doesn't like this, 192.168.100.2 -> Ubuntu (master) and 192.168.100.2 -> Teldat 

There is an IP conflict

**Comment by redbrain17** [comment]
here is the tcpdump for the three steps of the picture, spanning tree is disabled. 
yes there is IP Conflict buts it is because the vrrpd isn't switching back the state.  

     ############### Step 1
	13:19:03.614820 IP (tos 0x0, ttl 255, id 50457, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:04.614809 IP (tos 0x0, ttl 255, id 50458, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:05.614798 IP (tos 0x0, ttl 255, id 50459, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:06.614783 IP (tos 0x0, ttl 255, id 50462, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:07.614761 IP (tos 0x0, ttl 255, id 50463, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:08.614746 IP (tos 0x0, ttl 255, id 50464, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:09.614749 IP (tos 0x0, ttl 255, id 50466, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:10.614739 IP (tos 0x0, ttl 255, id 50467, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:11.614724 IP (tos 0x0, ttl 255, id 50469, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:12.614711 IP (tos 0x0, ttl 255, id 50471, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:13.614700 IP (tos 0x0, ttl 255, id 50472, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2

	############### Step 2
	13:19:17.228717 IP (tos 0x0, ttl 255, id 256, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.3 > 224.0.0.18: vrrp 192.168.100.3 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:18.363899 IP (tos 0x0, ttl 255, id 512, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.3 > 224.0.0.18: vrrp 192.168.100.3 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:19.367950 IP (tos 0x0, ttl 255, id 768, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.3 > 224.0.0.18: vrrp 192.168.100.3 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:19.432231 IP (tos 0x0, ttl 255, id 442, offset 0, flags [DF], proto UDP (17), length 141)
		192.168.100.3.5353 > 224.0.0.251.5353: [bad udp cksum 0x0632 -> 0x750d!] 0*- [0q] 3/0/0 2.100.168.192.in-addr.arpa. (Cache flush) [2m] PTR sebastian-OptiPlex-7010.local., sebastian-OptiPlex-7010.local. (Cache flush) [2m] A 192.168.100.2, sebastian-OptiPlex-7010.local. (Cache flush) [2m] A 192.168.100.3 (113)
	13:19:20.371948 IP (tos 0x0, ttl 255, id 1024, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.3 > 224.0.0.18: vrrp 192.168.100.3 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:21.373073 IP (tos 0x0, ttl 255, id 1280, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.3 > 224.0.0.18: vrrp 192.168.100.3 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:21.659599 IP (tos 0x0, ttl 255, id 800, offset 0, flags [DF], proto UDP (17), length 141)
		192.168.100.3.5353 > 224.0.0.251.5353: [bad udp cksum 0x0632 -> 0x750d!] 0*- [0q] 3/0/0 2.100.168.192.in-addr.arpa. (Cache flush) [2m] PTR sebastian-OptiPlex-7010.local., sebastian-OptiPlex-7010.local. (Cache flush) [2m] A 192.168.100.2, sebastian-OptiPlex-7010.local. (Cache flush) [2m] A 192.168.100.3 (113)
	13:19:22.375954 IP (tos 0x0, ttl 255, id 1536, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.3 > 224.0.0.18: vrrp 192.168.100.3 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:23.379943 IP (tos 0x0, ttl 255, id 1792, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.3 > 224.0.0.18: vrrp 192.168.100.3 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:24.381181 IP (tos 0x0, ttl 255, id 2048, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.3 > 224.0.0.18: vrrp 192.168.100.3 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20, addrs: 192.168.100.2

	############### Step 3
	13:19:25.241659 IP (tos 0x0, ttl 255, id 50479, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:25.382433 IP (tos 0x0, ttl 255, id 2304, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.3 > 224.0.0.18: vrrp 192.168.100.3 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:25.614573 IP (tos 0x0, ttl 255, id 50483, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:26.383958 IP (tos 0x0, ttl 255, id 2560, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.3 > 224.0.0.18: vrrp 192.168.100.3 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:26.614540 IP (tos 0x0, ttl 255, id 50484, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:27.385236 IP (tos 0x0, ttl 255, id 2816, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.3 > 224.0.0.18: vrrp 192.168.100.3 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:27.614553 IP (tos 0x0, ttl 255, id 50485, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:28.386613 IP (tos 0x0, ttl 255, id 3072, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.3 > 224.0.0.18: vrrp 192.168.100.3 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:28.614544 IP (tos 0x0, ttl 255, id 50486, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:29.391947 IP (tos 0x0, ttl 255, id 3328, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.3 > 224.0.0.18: vrrp 192.168.100.3 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:29.614527 IP (tos 0x0, ttl 255, id 50487, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.2 > 224.0.0.18: vrrp 192.168.100.2 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.2
	13:19:30.395935 IP (tos 0x0, ttl 255, id 3584, offset 0, flags [none], proto VRRP (112), length 40)
		192.168.100.3 > 224.0.0.18: vrrp 192.168.100.3 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20, addrs: 192.168.100.2

**Comment by fredbcode** [comment]
> yes there is IP Conflict buts it is because the vrrpd isn't switching back the state. 

No it's not what I mean at all

192.168.100.2 -> Should not emit packets, this is the VIP not a physical address 

Vrrpd is not magic, you can't have the same IP for both, only the VIP changes to computer A to B and B to A

They **must** speak with physical addresses and these addresses must be fixed and not the same

eg:
192.168.100.4 -> Teldat
192.168.100.3 -> ubuntu
192.168.100.1 -> VIP -> Master computer  

 Your configuration is wrong, fix Teldat (and reboot after I guess)

**Comment by redbrain17** [comment]
ok I got it, thanks a lot for your explanation.

**Comment by fredbcode** [comment]
it works ? I can close the ticket ?

**Comment by redbrain17** [comment]
your proposed config works, so yes you can close the ticket
