### ISSUE TITLE
Micro down time...

### ISSUE THREAD

**Issue by Fridus** [fredbcode/Vrrpd#12]
Hi,
In my tests, if I create a micro down time with `ifdown eth0 && ifup eth0`, I lose my vip.
I think it could be nice to make check if the virtual ip is attributed to a machine.

What is the option `-d` (delay)  ?

**Comment by fredbcode** [comment]
| In my tests, if I create a micro down time with ifdown eth0 && ifup eth0 , I lose my vip. 

Vrrpd is a very simple high-availability solution, the controls should be outside
eg : A script ping the VIP address if down -> atropos --backup 

However with -M 1 (monitoring process) if the link is down vrrpd should changes his state to Backup
But I'm not sure with a very short time ...
 

| What is the option -d (delay) ? 


The delay between the master and the backup, if master is down "delay value" seconds the Backup becomes Master

**Comment by Fridus** [comment]
Uptime is critical for me.
Sometimes, I've micro down time in my network ...

I think the deamon must check if vIP is down and the other machine is a life -> restart service.
No ?

**Comment by fredbcode** [comment]
| I think the deamon must check if vIP is down and the other machine is a life -> restart service. 
| No ? 


I don't understand right your problem  

Virtual address is not related with VRRPD, created only, you can see the address with ip show addr 

There is a big difference between link loose and short lan interruption, there is no usual situation with link down/up frequently 

Link loose (up and down) = related to computer the switch connected only, it's a case of failure VRRPD detects this and change his state to Backup (VIP down)
Lan problem = VRRPD can't communicate and the Backup switch to Master, but the both are Master very dangerous !

VRRPD works like this, on a LAN the Master broadcasts to the other(s) slave(s), if the slave can't show the packets it becomes master
The both must be on the same LAN and same switch (or hub) with a very reliable local lan transport (as all HA software I known)

HA communication with unstable LAN is not an option, at least with VRRP, MASTER and BACKUP should communicates or there is a failure and VRRPD do the job MASTER -> BACKUP


About restart service you can write something in MASTER/BACKUP scripts

**Comment by Fridus** [comment]
( Vous êtes français ? on peut continuer en fr ? )

**Comment by fredbcode** [comment]
ça se voit autant que ça ? :)

**Comment by Fridus** [comment]
-> C'est marqué sur votre profil ;)

Pourquoi ce n'est pas le deamon vrrp qui check si il faut repasser en master ? 
Dans mon cas je test avec des petite coupure parce que mes servers sont dans une baie virtuelle et de temps en temps je peux avoir des petites coupures... 
J'ai eu le problème aussi après une update des règles du firewall, il y a une mini coupure et les deux machines passe en "backup". Ca m'oblige à faire un restart du service vrrp sur les deux pour que tout revienne à la normale.

Je me disais que ça serait pas mal d'avoir un check permanent sur : 
- j'ai bien un master avec la vIP
- je vois les autres machines
afin de pouvoir relancer le service quand c'est planté

**Comment by Fridus** [comment]
Ca fonctionne avec plusieurs slave ? Pour faire un cluster sur 3 machines

**Comment by fredbcode** [comment]
VRRPD est normalisé (RFC) il fonctionne comme ça 

C'est bien le démon vrrpd qui check si il doit repasser Master, en ne recevant plus de Backup de l'autre dans ce cas la VIP tombe et bascule sur l'autre.
Concernant le Firewall vous pouvez allonger le délai vrrp (réglera surement aussi le point micro coupure) 
Par contre le besoin de restart n'est clairement pas normal, les deux doivent négocier et un devenir maitre et l'autre backup 

Si vous avez des pertes régulières entre vos deux équipements VRRPD , je pense que vrrpd ne conviendra pas à votre besoin, la connexion entre les deux serveurs doit être solide
Toute les autres situations sont des cas de pannes potentiels 

Vos machines sont des VM ? Si oui avez-vous des mac virtuelles ? C'est souvent incompatible et pose bien des soucis 

Oui plusieurs slaves, mais ce n'est pas un cluster c'est en mode actif/passif

**Comment by Fridus** [comment]
J'ai fait mes tests sur des VM virtualbox pour être sur que le système fonctionne. J'utilise le flag `-n` sinon ça frise ^^
En prod, ce sont des KVM. J'en ai 3 sur Heartbeat.
Malheureusement, je n'ai pas de garantie de pas avoir temps à autre une petite perte... Ce sont les vrack d'OVH...

Le seul soucis que j'ai pour le moment, c'est à cause des coupures. je vais augmenter le delay à 5s et ajouter un noeud.
Si ça marche, je reproduit ça sur le réseau de prod.

VRRPD est plus adapté que heartbeat pour mes besoins avec ces machines ci...

**Comment by fredbcode** [comment]
Ok je laisse le ticket ouvert pour l'instant 

Pour mon info les KVM fonctionnent avec la mac virtuelle ? 
Le délai devrait résoudre ton problème toutefois il y a une chose qui reste étrange, au retour du réseau tu ne devrais pas avoir besoin de relancer le service visiblement quelque chose ne fonctionne pas correctement ...

Tu peux regarder aussi au niveau de la priorité si tu préfères qu'une machine soit Master, en cas de situation "normale" elle prendra toujours la main sur les autres

Et n'oublie d'user et d'abuser d'atropos, y compris dans tes scripts de supervision

**Comment by fredbcode** [comment]
> VRRPD est plus adapté que heartbeat pour mes besoins avec ces machines ci...

Pourquoi ?

**Comment by Fridus** [comment]
Vous pouvez juste me donner une petite précision sur les option `-I` et `-O`. C'est bien pour spécifier les carte qui sont liées pour la communication "alive" ?

La configuration de Heartbeat se base permet de démarrer ou stopper des services quand une machine passe slave ou master.
Avec vrrpd, c'est clairement des scripts. 
Mon besoin c'est de binder des plages d'ip aux machines et ça doit être HA.

Vu l'heure , le test sera lancé au matin ;)

**Comment by fredbcode** [comment]
Non 

-i c'est l'interface 
-I et -O sont des modes avancés qui permettent d'envoyer des paquets au routeur (inutile dans votre cas)

Oui les IP alias fonctionnent très bien, attention à bien les démonter dans le script Backup sinon c'est vite le mode catastrophe ...

**Comment by Fridus** [comment]
Bonjour,

J'ai fait le test avec 3 machines et le delay plus haut (5).
Le problème de la petite coupure `ifdown eth0; ifup eth0` est tjs là.

Autre cas de figure: coupure plus longue que le délai `ifdown eth0; sleep 7; ifup eth0`.
Dans ce cas le switch vers un slave se passe bien.

Mon hypothèse c'est que si la coupure est plus petite que le délai, le master passe en slave sans autre élection de master. 
Mon test avec le delay à `5s`:
- Plus grand que le délai:  `ifdown eth0; sleep 7 ; ifup eth0` -> OK
- Egual au délai : `ifdown eth0; sleep 5 ; ifup eth0` -> OK
- Plus petit que le délai: `ifdown eth0; sleep 4 ; ifup eth0` -> Le problème ...

**Comment by Fridus** [comment]
La machine concernée reste en mode `MASTER` et les deux autres en `SLAVE`.
L'état revient à la normale que si la machine MASTER la commande `atropos --backup` est lancée. (Ou `service vrrp restart` mais bcp plus long).

**Comment by fredbcode** [comment]
Votre problème à l'origine c'est bien des pertes réseaux ou alors des pertes de Link (je veux dire par là câble débranché) ?
Si c'est vraiment des pertes du Link (ifup down ou câble débranché) j'ai bien peur que ce soit difficile à contourner, mais est-ce un test réaliste ?

| Mon hypothèse c'est que si la coupure est plus petite que le délai, le master passe en slave sans autre élection de master. 

Oui complétement normal, le délai fonctionne comme ça, si le Backup ne voit pas le Master pendant x secondes il passe maitre
En attendant le Master détecte une panne (Link down) et il passe backup

Délais 1 seconde -> Pas de Master pendant 1 seconde je passe maitre 
Délais 2 secondes -> Pas de Master pendant 2 secondes je passe maitre 
Etc 

Le maître VRRPD envoi des paquets sur l'adresse multicast 224.0.0.18 , ainsi il indique au Backup qu'il est en vie  

Quand vous faite un ifup down, dans syslog vous devez avoir des informations indiquant une perte de Link, la distrib n'est pas contente et génère des actions (et on ne pourra rien faire contre ça), ensuite VRRPD indique qu'il y a un souci et passe Backup, je suppose que normalement votre problème est différent, il s'agit plutôt de pertes de paquets entre les deux machines mais sans perte de Link ?

**Comment by Fridus** [comment]
J'ai refait le réseau sur ma prod et ça fonctionne ! :) (en KVM avec le flag `-n`)

> En attendant le Master détecte une panne (Link down) et il passe backup

Quand le problème se présente (avec ifdown) je constate que le master reste avec le status de master via `atropos --state`. Donc il ne passe pas réellement en slave. Le problème vie peut-être juste de là ?

**Comment by fredbcode** [comment]
Oui surement ce n'est pas un test réaliste à mon avis, je cloture ?

**Comment by Fridus** [comment]
Vous utilisez qqch pour le monitoring de le rescue sur vos servers par rapport à vrrp ? Je vais ajouter du monitoring pour surveillez ça ^^
J'espère que ce n'est pas un cas de figure qui peut arriver en prod.

PS: le script `install.sh` copie des ficher d'un dossier `scripts` qui n'existe pas.
