### ISSUE TITLE
Multiple virtual servers on single link

### ISSUE THREAD

**Issue by PeterWiggins84** [fredbcode/Vrrpd#15]
I have a single instance running just fine as you can see below.

admin@provo-baby:> ps aux | grep vrrp

> root      49366  0.0  0.0   8512  1612 ?        Ss   01:57   0:00 /usr/sbin/vrrpd -n -p 150 -i public -v 20 10.10.100.101 24
> admin     50799  0.0  0.0   8992   960 pts/1    S+   02:15   0:00 grep vrrp

admin@provo-baby:> ip addr show public

> 6: public: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
>     link/ether xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
>     inet 10.243.5.135/24 brd 10.243.5.255 scope global public
>        valid_lft forever preferred_lft forever
>     inet 10.10.100.101/24 brd 10.10.100.255 scope global public
>        valid_lft forever preferred_lft forever
>     inet6 fe80::21e:67ff:fef2:de5c/64 scope link
>        valid_lft forever preferred_lft forever

When I try to start another virtual server on the same node + link, it fails to do much of anything

admin@provo-baby:> sudo /usr/sbin/vrrpd -n -p 150 -i public -v 21 10.10.10.100.102/24
admin@provo-baby:> ps aux | grep vrrp

> root      49366  0.0  0.0   8512  1612 ?        Ss   01:57   0:00 /usr/sbin/vrrpd -n -p 150 -i public -v 20 10.10.100.101 24
> admin     51265  0.0  0.0   8992   972 pts/1    S+   02:17   0:00 grep vrrp

admin@provo-baby:> ip addr show public

> 6: public: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
>     link/ether  xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
>     inet 10.243.5.135/24 brd 10.243.5.255 scope global public
>        valid_lft forever preferred_lft forever
>     inet 10.10.100.101/24 brd 10.10.100.255 scope global public
>        valid_lft forever preferred_lft forever
>     inet6 fe80::21e:67ff:fef2:de5c/64 scope link
>        valid_lft forever preferred_lft forever

I am assuming I am not using the options correctly as the virtual server ID seems to be specifically for this use case (along with the -n).

I was running 1.12 and updated to the latest 1.15 to the same result.
The only difference I see is in 1.15 I get an error message of "Socket already used by public, exit"

**Comment by fredbcode** [comment]
public is the nic name ? id must be the same on each computer |
|

|Something like this
|

|provo-baby1 |
||/usr/sbin/vrrpd -n -p 150 -i eth0 -v 20 10.10.100.101||

|provo-baby2|
|||/usr/sbin/vrrpd -n -p 150 -i eth0 -v 20 10.10.100.101|||
|||
|||
|||When the master "provo-baby" is shutdown ||||||||10.10.100.101 switch 
to the other automatically
|||||
|||||
|||||
|||||If you are also using a second couple of nic (eg eth1) ID must be 
different|||||
|||||||
|||||
|||||||/usr/sbin/vrrpd -n -p 150 -i eth0 -v 20 10.10.100.101|||||||
|||||||||/usr/sbin/vrrpd -n -p 150 -i eth0 -v 20 10.10.100.101|||||||| |

||/usr/sbin/vrrpd -n -p 150 -i eth1 -v 21 10.10.100.101||
||||/usr/sbin/vrrpd -n -p 150 -i eth0 -v 21 10.10.100.101||||
||||
||||
||||ID is the link between couple of ||||||||||VRRPD||||||
||||||
|| ||||

**Comment by PeterWiggins84** [comment]
I was looking to manage multiple IPs. As in have 4 IPs A, B, C, D. 
When nodeX is the master all 4 IPs should be running. 
If a higher priority node comes online (or current master goes down) id want all 4 IPs to move to new master. 
Is this possible? All 4 IPs would be on the same public interface.

**Comment by fredbcode** [comment]
Yes of course, you can add multiples virtual IPs

But in this case it's better to use script in change state (-U, -D), in -UP you add ip alias -D you down thee virtual alias

When VRRPD is master, it launch the up (-U) script with IP alias and when VRRPD is down it launch the down script (-D) and remove the IPs

**Comment by fredbcode** [comment]
Server1
/usr/sbin/vrrpd -n -p 150 -i eth0 -U /etc/vrrpd/up_script -D /etc/vrrpd/down_script -v 20

Server2
/usr/sbin/vrrpd -n -p 100 -i eth0 -U /etc/vrrpd/up_script -D /etc/vrrpd/down_script -v 20

I reduced the priority to server2, server1 is the master in usual case

**Comment by fredbcode** [comment]
Addresses are now in up_script and removed in down_script

Another tracks you can "links" the interfaces in same computer

A
/usr/sbin/vrrpd -n -p 150 -i eth0 -M 2 -v 20 10.10.100.101 
/usr/sbin/vrrpd -n -p 150 -i eth1 -M 2 -v 20 10.10.100.101 

B
/usr/sbin/vrrpd -n -p 150 -i eth0 -M 2 -v 21 10.10.100.101 
/usr/sbin/vrrpd -n -p 150 -i eth1 -M 2 -v 21 10.10.100.101

-M 2 means monitoring the two nics if one is down (eg link) the second will be also down

**Comment by fredbcode** [comment]
I can close ?

**Comment by PeterWiggins84** [comment]
Yes, thank you for the additional information!
