### ISSUE TITLE
Cross Compile Issue

### ISSUE THREAD

**Issue by redbrain17** [fredbcode/Vrrpd#8]
To cross-compile Vrrpd for my ARM architecture I need to adapt the Makefile

-CC = gcc
+CC = arm-v5te-linux-gnueabi-gcc

is there a way to generalize that for other architectures?

**Comment by fredbcode** [comment]
Vrrpd is a very simple program, for the moment there is not configure file (or something like that)
For ARM I will put a word in README

**Comment by fredbcode** [comment]
For my information, witch platform exactly ? I never tested vrrpd on ARM

**Comment by redbrain17** [comment]
Ok fine I got it compiled for my Arm successfuly with that liitle change. and the fix for the linking problem

**Comment by redbrain17** [comment]
Freescale IMX28 ARM 9 Cortex

**Comment by fredbcode** [comment]
Linux ?

**Comment by redbrain17** [comment]
a ptxdist based linux build for embedded devices

http://www.pengutronix.de/software/ptxdist/

**Comment by fredbcode** [comment]
Interesting, thanks
