### ISSUE TITLE
undefined reference to clock_gettime" with some OS

### ISSUE THREAD

**Issue by redbrain17** [fredbcode/Vrrpd#9]
On my platform I need to move the -lrt option to the end of line to get the linking error away

undefined reference to clock_gettime" with some OS

-       $(CC) $(PROF_OPT) -o $@ -lrt $^
+       $(CC) $(PROF_OPT) -o $@ $^ -lrt

after that change it works for me

**Comment by fredbcode** [comment]
Atropos line 29 ?

**Comment by redbrain17** [comment]
yes line 29

**Comment by fredbcode** [comment]
Ok fixed thanks
